import { test, expect, signIn, uniqueCode, seedEncounter, openPatient, choosePlacement } from './support.js';

test('birth and admission dates use server rules even when the browser clock is behind', async ({ page, operatorApi }) => {
  const mrn = uniqueCode('BIRTH');
  const today = new Date().toISOString().slice(0, 10);
  const tomorrow = new Date(Date.now() + 86_400_000).toISOString().slice(0, 10);
  await page.clock.setFixedTime(new Date('2000-01-01T12:00:00Z'));
  await signIn(page);
  await page.getByRole('button', { name: 'Register patient', exact: true }).click();
  await page.getByLabel('Medical record number', { exact: true }).fill(mrn);
  await page.getByLabel('First name', { exact: true }).fill('Newborn');
  await page.getByLabel('Last name', { exact: true }).fill('Test');
  await page.getByLabel('Date of birth', { exact: true }).fill(tomorrow);
  await page.getByRole('button', { name: 'Save patient', exact: true }).click();
  await expect(page.locator('#dateOfBirth-error')).toHaveText('Date of birth cannot be in the future');
  await page.getByLabel('Date of birth', { exact: true }).fill(today);
  await page.getByRole('button', { name: 'Save patient', exact: true }).click();
  await expect(page.locator('#registration-dialog')).not.toBeVisible();
  await openPatient(page, mrn);
  await page.getByRole('button', { name: 'Admit patient', exact: true }).click();
  await page.getByLabel('Encounter number', { exact: true }).fill(uniqueCode('BEFORE-BIRTH'));
  await page.getByLabel('Admission time', { exact: true }).fill('1999-01-01T12:00');
  await page.getByRole('button', { name: 'Save admission', exact: true }).click();
  await expect(page.locator('#admittedAt-error')).toHaveText("Admission date cannot be before the patient's date of birth");
  const { items: [patient] } = await operatorApi.get(`/api/v1/patients?keyword=${mrn}`);
  expect((await operatorApi.get(`/api/v1/patients/${patient.id}/encounters`)).totalElements).toBe(0);
});

test('operator registers, admits, places, transfers and discharges a patient through the workbench', async ({ page, operatorApi }) => {
  const mrn = uniqueCode('MRN');
  const number = uniqueCode('ENC');
  const departments = await operatorApi.get('/api/v1/departments?active=true');
  const wards = await operatorApi.get('/api/v1/wards?active=true');
  const [bed] = await operatorApi.get(`/api/v1/beds?wardId=${wards[0].id}&active=true&occupied=false`);
  await signIn(page);
  await page.getByRole('button', { name: 'Register patient', exact: true }).click();
  await page.getByLabel('Medical record number', { exact: true }).fill(mrn);
  await page.getByLabel('First name', { exact: true }).fill('Browser');
  await page.getByLabel('Last name', { exact: true }).fill('Workflow');
  await page.getByLabel('Date of birth', { exact: true }).fill('1990-01-01');
  await page.getByRole('button', { name: 'Save patient', exact: true }).click();
  await expect(page.locator('#registration-dialog')).not.toBeVisible();
  await openPatient(page, mrn);
  await page.getByRole('button', { name: 'Admit patient', exact: true }).click();
  await page.getByLabel('Encounter number', { exact: true }).fill(number);
  await page.getByRole('button', { name: 'Save admission', exact: true }).click();
  const row = page.locator('#encounter-rows tr').filter({ hasText: number });
  await row.getByRole('button', { name: /^Enter department for / }).click();
  await choosePlacement(page, departments[0].id, wards[0].id, bed.id);
  await page.getByRole('button', { name: 'Save department entry', exact: true }).click();
  await expect(page.locator('#department-dialog')).not.toBeVisible();
  expect((await operatorApi.get(`/api/v1/beds/${bed.id}`)).occupied).toBe(true);
  await row.getByRole('button', { name: /^Transfer for / }).click();
  await choosePlacement(page, departments[1].id, wards[1].id);
  await page.getByRole('button', { name: 'Save transfer', exact: true }).click();
  await expect(page.locator('#department-dialog')).not.toBeVisible();
  expect((await operatorApi.get(`/api/v1/beds/${bed.id}`)).occupied).toBe(false);
  await row.getByRole('button', { name: /^Discharge for / }).click();
  await page.getByRole('button', { name: 'Save discharge', exact: true }).click();
  await expect(page.locator('#discharge-dialog')).not.toBeVisible();
  await expect(row.locator('.encounter-status')).toHaveText('Discharged');
  await row.getByRole('button', { name: /^Timeline for / }).click();
  await expect(page.locator('#timeline-status')).toHaveText('Discharged');
  await expect(page.locator('#timeline-location-rows tr')).toHaveCount(2);
  await expect(page.locator('#timeline-discharge-rows tr')).toHaveCount(1);
  const patients = await operatorApi.get(`/api/v1/patients?keyword=${mrn}`);
  const history = await operatorApi.get(`/api/v1/patients/${patients.items[0].id}/encounters`);
  expect(history.items).toHaveLength(1);
  const timeline = await operatorApi.get(`/api/v1/encounters/${history.items[0].id}/timeline`);
  expect(timeline.locations.every(location => location.endedAt !== null)).toBeTruthy();
  expect(timeline.locations.map(location => location.bedId)).toContain(bed.id);
  expect(timeline.locations.map(location => location.bedId)).toContain(null);
  expect(timeline.encounter.status).toBe('DISCHARGED');
});

test('cancelled admission stays in patient history and leaves the inpatient worklist', async ({ page, operatorApi }) => {
  const { patient, encounter } = await seedEncounter(operatorApi, { placed: false });
  await signIn(page);
  await openPatient(page, patient.medicalRecordNumber);
  const row = page.locator('#encounter-rows tr').filter({ hasText: encounter.encounterNumber });
  await row.getByRole('button', { name: /^Cancel admission for / }).click();
  await page.getByRole('button', { name: 'Confirm cancellation', exact: true }).click();
  await expect(page.locator('#admission-cancellation-dialog')).not.toBeVisible();
  await expect(row).toContainText('Admission cancelled');
  await row.getByRole('button', { name: /^Timeline for / }).click();
  await expect(page.locator('#timeline-status')).toHaveText('Admission cancelled');
  await expect(page.locator('#timeline-admission-operator')).toHaveText('operator');
  const inpatients = await operatorApi.get(`/api/v1/inpatients?keyword=${encounter.encounterNumber}`);
  expect(inpatients.totalElements).toBe(0);
});
