package com.jiangyudai.clinicflow.persistence;

import org.flywaydb.core.Flyway;
import org.flywaydb.core.api.FlywayException;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestInstance;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.ValueSource;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.annotation.DirtiesContext;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.DynamicPropertyRegistry;
import org.springframework.test.context.DynamicPropertySource;

import java.time.OffsetDateTime;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.NONE)
@ActiveProfiles("postgres")
@TestInstance(TestInstance.Lifecycle.PER_CLASS)
@DirtiesContext(classMode = DirtiesContext.ClassMode.AFTER_CLASS)
class PostgresInpatientIntegrityIT {

    private static final String SCHEMA = "clinicflow_integrity_" + UUID.randomUUID().toString().replace("-", "");
    private static final OffsetDateTime START = OffsetDateTime.parse("2025-09-01T10:00:00-04:00");
    private static final List<String> TABLES = List.of("patients", "departments", "wards", "beds",
            "encounters", "encounter_locations", "encounter_discharges", "physicians",
            "physician_departments", "encounter_physician_assignments");

    @Autowired
    private JdbcTemplate jdbc;

    @DynamicPropertySource
    static void databaseProperties(DynamicPropertyRegistry properties) {
        String url = System.getenv("TEST_DATABASE_URL");
        boolean external = url != null && !url.isBlank();
        if (external && !url.startsWith("jdbc:postgresql://")) {
            throw new IllegalArgumentException("TEST_DATABASE_URL must be a PostgreSQL JDBC URL");
        }
        String username = external ? requiredEnvironment("TEST_DATABASE_USERNAME") : "test";
        String password = external ? requiredEnvironment("TEST_DATABASE_PASSWORD") : "test";
        properties.add("spring.datasource.url", () -> external ? url : "jdbc:tc:postgresql:17:///clinicflow");
        properties.add("spring.datasource.username", () -> username);
        properties.add("spring.datasource.password", () -> password);
        properties.add("spring.datasource.driver-class-name", () -> external
                ? "org.postgresql.Driver" : "org.testcontainers.jdbc.ContainerDatabaseDriver");
        properties.add("spring.datasource.hikari.schema", () -> SCHEMA);
        properties.add("spring.flyway.default-schema", () -> SCHEMA);
        properties.add("spring.flyway.schemas", () -> SCHEMA);
        properties.add("spring.jpa.properties.hibernate.default_schema", () -> SCHEMA);
    }

    @AfterAll
    void removeTestSchema() {
        // Schema names are generated by this test, never supplied by the environment.
        jdbc.execute("DROP SCHEMA " + SCHEMA + " CASCADE");
    }

    @Test
    void upgradesVersionSixWithoutChangingHistoryAndDoesNotReapply() {
        String schema = migrationSchema();
        try {
            migrateTo(schema, "6").migrate();
            Fixture fixture = fixture(schema);
            UUID original = location(schema, fixture.encounter(), fixture, fixture.bed(), START, START.plusHours(1));
            UUID restored = location(schema, fixture.encounter(), fixture, fixture.bed(), START.plusHours(1), null);
            jdbc.update("INSERT INTO " + schema + ".encounter_discharges "
                            + "(id, encounter_id, location_id, discharged_at, cancelled_at, cancelled_by, restored_location_id) "
                            + "VALUES (?, ?, ?, ?, ?, 'test-clerk', ?)",
                    UUID.randomUUID(), fixture.encounter(), original, START.plusHours(1), START.plusHours(2), restored);
            UUID physician = UUID.randomUUID();
            jdbc.update("INSERT INTO " + schema + ".physicians "
                            + "(id, physician_code, first_name, last_name, active, version) VALUES (?, ?, 'Test', 'Doctor', true, 0)",
                    physician, physician.toString().substring(0, 20));
            jdbc.update("INSERT INTO " + schema + ".physician_departments (physician_id, department_id) VALUES (?, ?)",
                    physician, fixture.department());
            jdbc.update("INSERT INTO " + schema + ".encounter_physician_assignments "
                            + "(id, encounter_id, physician_id, department_id, started_at, assigned_by, version) "
                            + "VALUES (?, ?, ?, ?, ?, 'test-clerk', 0)",
                    UUID.randomUUID(), fixture.encounter(), physician, fixture.department(), START.plusHours(2));
            var before = snapshot(schema);

            Flyway upgrade = migrateTo(schema, "7");
            assertThat(upgrade.migrate().migrationsExecuted).isEqualTo(1);
            assertThat(upgrade.migrate().migrationsExecuted).isZero();
            assertThat(snapshot(schema)).isEqualTo(before);
            assertThat(jdbc.queryForObject("SELECT count(*) FROM " + schema
                    + ".flyway_schema_history WHERE version = '7' AND success", Integer.class)).isEqualTo(1);
            assertThatThrownBy(() -> location(schema, fixture.encounter(), fixture, null, START.plusHours(3), null))
                    .isInstanceOf(DataIntegrityViolationException.class)
                    .hasMessageContaining("uk_encounter_locations_open_encounter");
        } finally {
            jdbc.execute("DROP SCHEMA IF EXISTS " + schema + " CASCADE");
        }
    }

    @ParameterizedTest
    @ValueSource(strings = {"active-patient", "open-encounter", "open-bed", "negative-time"})
    void refusesInvalidLegacyDataWithoutChangingRecordsOrInstallingPartialConstraints(String problem) {
        String schema = migrationSchema();
        try {
            migrateTo(schema, "6").migrate();
            Fixture fixture = fixture(schema);
            location(schema, fixture.encounter(), fixture, fixture.bed(), START, null);
            String message = switch (problem) {
                case "active-patient" -> {
                    encounter(schema, fixture.patient(), "ADMITTED");
                    yield "A patient has multiple active encounters";
                }
                case "open-encounter" -> {
                    location(schema, fixture.encounter(), fixture, null, START.plusHours(1), null);
                    yield "An encounter has multiple open locations";
                }
                case "open-bed" -> {
                    location(schema, encounter(schema, patient(schema), "IN_DEPARTMENT"), fixture, fixture.bed(), START, null);
                    yield "A bed has multiple open occupancies";
                }
                case "negative-time" -> {
                    location(schema, fixture.encounter(), fixture, null, START, START.minusSeconds(1));
                    yield "A location ends before it starts";
                }
                default -> throw new IllegalArgumentException(problem);
            };
            var before = snapshot(schema);

            assertThatThrownBy(() -> migrateTo(schema, "7").migrate())
                    .isInstanceOf(FlywayException.class).hasStackTraceContaining(message);

            assertThat(snapshot(schema)).isEqualTo(before);
            assertThat(jdbc.queryForObject("SELECT count(*) FROM " + schema
                    + ".flyway_schema_history WHERE version = '7'", Integer.class)).isZero();
            assertThat(jdbc.queryForList("SELECT indexname FROM pg_indexes WHERE schemaname = ?", String.class, schema))
                    .doesNotContain("uk_encounters_active_patient", "uk_encounter_locations_open_encounter",
                            "uk_encounter_locations_open_bed");
            assertThat(jdbc.queryForObject("SELECT count(*) FROM pg_constraint c JOIN pg_namespace n ON n.oid = c.connamespace "
                    + "WHERE n.nspname = ? AND c.conname = 'ck_encounter_locations_time'", Integer.class, schema)).isZero();
        } finally {
            jdbc.execute("DROP SCHEMA IF EXISTS " + schema + " CASCADE");
        }
    }

    @ParameterizedTest
    @ValueSource(strings = {"ADMITTED", "IN_DEPARTMENT"})
    void rejectsAnotherActiveEncounterOnInsertAndReactivation(String activeStatus) {
        UUID patient = patient(SCHEMA);
        encounter(SCHEMA, patient, activeStatus);
        assertThatThrownBy(() -> encounter(SCHEMA, patient, "ADMITTED"))
                .isInstanceOf(DataIntegrityViolationException.class).hasMessageContaining("uk_encounters_active_patient");
        UUID closed = encounter(SCHEMA, patient, "DISCHARGED");
        assertThatThrownBy(() -> jdbc.update("UPDATE encounters SET status = 'IN_DEPARTMENT' WHERE id = ?", closed))
                .isInstanceOf(DataIntegrityViolationException.class).hasMessageContaining("uk_encounters_active_patient");
        assertThat(jdbc.queryForObject("SELECT status FROM encounters WHERE id = ?", String.class, closed)).isEqualTo("DISCHARGED");
    }

    @Test
    void rejectsAnotherOpenLocationOnInsertAndReopening() {
        Fixture fixture = fixture(SCHEMA);
        location(SCHEMA, fixture.encounter(), fixture, fixture.bed(), START, null);
        assertThatThrownBy(() -> location(SCHEMA, fixture.encounter(), fixture, null, START, null))
                .isInstanceOf(DataIntegrityViolationException.class).hasMessageContaining("uk_encounter_locations_open_encounter");
        UUID closed = location(SCHEMA, fixture.encounter(), fixture, null, START.minusHours(1), START);
        assertThatThrownBy(() -> jdbc.update("UPDATE encounter_locations SET ended_at = NULL WHERE id = ?", closed))
                .isInstanceOf(DataIntegrityViolationException.class).hasMessageContaining("uk_encounter_locations_open_encounter");
        assertThat(jdbc.queryForObject("SELECT ended_at FROM encounter_locations WHERE id = ?", OffsetDateTime.class, closed))
                .isEqualTo(START);
    }

    @Test
    void rejectsAnotherOpenBedOccupancyOnInsertAndBedChange() {
        Fixture fixture = fixture(SCHEMA);
        location(SCHEMA, fixture.encounter(), fixture, fixture.bed(), START, null);
        UUID otherEncounter = encounter(SCHEMA, patient(SCHEMA), "IN_DEPARTMENT");
        assertThatThrownBy(() -> location(SCHEMA, otherEncounter, fixture, fixture.bed(), START, null))
                .isInstanceOf(DataIntegrityViolationException.class).hasMessageContaining("uk_encounter_locations_open_bed");
        UUID unassigned = location(SCHEMA, otherEncounter, fixture, null, START, null);
        assertThatThrownBy(() -> jdbc.update("UPDATE encounter_locations SET bed_id = ? WHERE id = ?", fixture.bed(), unassigned))
                .isInstanceOf(DataIntegrityViolationException.class).hasMessageContaining("uk_encounter_locations_open_bed");
        assertThat(jdbc.queryForObject("SELECT bed_id FROM encounter_locations WHERE id = ?", UUID.class, unassigned)).isNull();
    }

    @Test
    void allowsClosedEncountersRepeatedBedHistoryAndMultipleUnassignedPatients() {
        Fixture fixture = fixture(SCHEMA);
        encounter(SCHEMA, fixture.patient(), "DISCHARGED");
        encounter(SCHEMA, fixture.patient(), "DISCHARGED");
        encounter(SCHEMA, fixture.patient(), "ADMISSION_CANCELLED");
        location(SCHEMA, fixture.encounter(), fixture, fixture.bed(), START.minusHours(1), START);
        location(SCHEMA, fixture.encounter(), fixture, fixture.bed(), START, START); // Equal-time corrections are valid.
        location(SCHEMA, fixture.encounter(), fixture, null, START, null);
        UUID other = encounter(SCHEMA, patient(SCHEMA), "IN_DEPARTMENT");
        location(SCHEMA, other, fixture, null, START, null);
        UUID third = encounter(SCHEMA, patient(SCHEMA), "IN_DEPARTMENT");
        location(SCHEMA, third, fixture, fixture.bed(), START, null);
        assertThat(jdbc.queryForObject("SELECT count(*) FROM encounter_locations WHERE ward_id = ? AND ended_at IS NULL",
                Integer.class, fixture.ward())).isEqualTo(3);
    }

    @Test
    void rejectsNegativeLocationIntervalsOnInsertAndUpdate() {
        Fixture fixture = fixture(SCHEMA);
        assertThatThrownBy(() -> location(SCHEMA, fixture.encounter(), fixture, null, START, START.minusNanos(1000)))
                .isInstanceOf(DataIntegrityViolationException.class).hasMessageContaining("ck_encounter_locations_time");
        UUID open = location(SCHEMA, fixture.encounter(), fixture, null, START, null);
        assertThatThrownBy(() -> jdbc.update("UPDATE encounter_locations SET ended_at = ? WHERE id = ?", START.minusSeconds(1), open))
                .isInstanceOf(DataIntegrityViolationException.class).hasMessageContaining("ck_encounter_locations_time");
        jdbc.update("UPDATE encounter_locations SET ended_at = started_at WHERE id = ?", open);
        assertThatThrownBy(() -> jdbc.update("UPDATE encounter_locations SET started_at = ? WHERE id = ?", START.plusSeconds(1), open))
                .isInstanceOf(DataIntegrityViolationException.class).hasMessageContaining("ck_encounter_locations_time");
    }

    private Flyway migrateTo(String schema, String version) {
        return Flyway.configure().dataSource(jdbc.getDataSource()).locations("classpath:db/migration/postgresql")
                .schemas(schema).defaultSchema(schema).target(version).load();
    }

    private Map<String, List<Map<String, Object>>> snapshot(String schema) {
        var result = new LinkedHashMap<String, List<Map<String, Object>>>();
        for (String table : TABLES) {
            result.put(table, jdbc.queryForList("SELECT * FROM " + schema + "." + table + " ORDER BY 1, 2"));
        }
        return result;
    }

    private UUID patient(String schema) {
        UUID id = UUID.randomUUID();
        jdbc.update("INSERT INTO " + schema + ".patients VALUES (?, ?, 'Test', 'Patient', DATE '1990-05-14')", id, id.toString());
        return id;
    }

    private UUID encounter(String schema, UUID patient, String status) {
        UUID id = UUID.randomUUID();
        jdbc.update("INSERT INTO " + schema + ".encounters (id, encounter_number, patient_id, status, admitted_at) "
                + "VALUES (?, ?, ?, ?, ?)", id, id.toString(), patient, status, START.minusHours(1));
        return id;
    }

    private Fixture fixture(String schema) {
        UUID department = UUID.randomUUID();
        UUID ward = UUID.randomUUID();
        UUID bed = UUID.randomUUID();
        jdbc.update("INSERT INTO " + schema + ".departments VALUES (?, ?, 'Test Medicine', true)", department, department.toString().substring(0, 20));
        jdbc.update("INSERT INTO " + schema + ".wards VALUES (?, ?, 'Test Ward', true)", ward, ward.toString().substring(0, 20));
        jdbc.update("INSERT INTO " + schema + ".beds VALUES (?, '01', ?, true)", bed, ward);
        UUID patient = patient(schema);
        return new Fixture(patient, encounter(schema, patient, "IN_DEPARTMENT"), department, ward, bed);
    }

    private UUID location(String schema, UUID encounter, Fixture fixture, UUID bed, OffsetDateTime start, OffsetDateTime end) {
        UUID id = UUID.randomUUID();
        jdbc.update("INSERT INTO " + schema + ".encounter_locations "
                + "(id, encounter_id, department_id, ward_id, bed_id, started_at, ended_at) VALUES (?, ?, ?, ?, ?, ?, ?)",
                id, encounter, fixture.department(), fixture.ward(), bed, start, end);
        return id;
    }

    private static String migrationSchema() {
        return "clinicflow_v7_" + UUID.randomUUID().toString().replace("-", "");
    }

    private static String requiredEnvironment(String name) {
        String value = System.getenv(name);
        if (value == null || value.isBlank()) {
            throw new IllegalArgumentException(name + " is required when TEST_DATABASE_URL is set");
        }
        return value;
    }

    private record Fixture(UUID patient, UUID encounter, UUID department, UUID ward, UUID bed) {
    }
}
