package com.jiangyudai.clinicflow.persistence;

import com.jiangyudai.clinicflow.encounter.entity.EncounterStatus;
import com.jiangyudai.clinicflow.encounter.entity.PhysicianAssignmentEndReason;
import com.jiangyudai.clinicflow.encounter.exception.ActiveEncounterExistsException;
import com.jiangyudai.clinicflow.encounter.service.EncounterPhysicianService;
import com.jiangyudai.clinicflow.encounter.service.EncounterService;
import jakarta.persistence.EntityManager;
import jakarta.persistence.PersistenceContext;
import org.flywaydb.core.Flyway;
import org.flywaydb.core.api.FlywayException;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestInstance;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.CsvSource;
import org.junit.jupiter.params.provider.ValueSource;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.annotation.DirtiesContext;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.DynamicPropertyRegistry;
import org.springframework.test.context.DynamicPropertySource;
import org.springframework.transaction.PlatformTransactionManager;
import org.springframework.transaction.support.TransactionTemplate;

import java.time.OffsetDateTime;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.UUID;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.ExecutionException;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.function.Supplier;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.NONE)
@ActiveProfiles("postgres")
@TestInstance(TestInstance.Lifecycle.PER_CLASS)
@DirtiesContext(classMode = DirtiesContext.ClassMode.AFTER_CLASS)
class PostgresInpatientIntegrityIT {

    private static final String SCHEMA = "clinicflow_integrity_" + UUID.randomUUID().toString().replace("-", "");
    private static final OffsetDateTime START = OffsetDateTime.parse("2025-09-01T10:00:00-04:00");
    private static final List<String> TABLES = List.of("patients", "departments", "wards", "beds",
            "encounters", "encounter_locations", "encounter_discharges", "physicians",
            "physician_departments", "encounter_physician_assignments");

    @Autowired
    private JdbcTemplate jdbc;
    @Autowired
    private PlatformTransactionManager transactionManager;
    @Autowired
    private EncounterService encounterService;
    @Autowired
    private EncounterPhysicianService physicianService;
    @PersistenceContext
    private EntityManager entityManager;

    @DynamicPropertySource
    static void databaseProperties(DynamicPropertyRegistry properties) {
        String url = System.getenv("TEST_DATABASE_URL");
        boolean external = url != null && !url.isBlank();
        if (external && !url.startsWith("jdbc:postgresql://")) {
            throw new IllegalArgumentException("TEST_DATABASE_URL must be a PostgreSQL JDBC URL");
        }
        String username = external ? requiredEnvironment("TEST_DATABASE_USERNAME") : "test";
        String password = external ? requiredEnvironment("TEST_DATABASE_PASSWORD") : "test";
        properties.add("spring.datasource.url", () -> external ? url : "jdbc:tc:postgresql:17:///clinicflow");
        properties.add("spring.datasource.username", () -> username);
        properties.add("spring.datasource.password", () -> password);
        properties.add("spring.datasource.driver-class-name", () -> external
                ? "org.postgresql.Driver" : "org.testcontainers.jdbc.ContainerDatabaseDriver");
        properties.add("spring.datasource.hikari.schema", () -> SCHEMA);
        properties.add("spring.flyway.default-schema", () -> SCHEMA);
        properties.add("spring.flyway.schemas", () -> SCHEMA);
        properties.add("spring.jpa.properties.hibernate.default_schema", () -> SCHEMA);
    }

    @AfterAll
    void removeTestSchema() {
        // Schema names are generated by this test, never supplied by the environment.
        jdbc.execute("DROP SCHEMA " + SCHEMA + " CASCADE");
    }

    @Test
    void upgradesVersionSixWithoutChangingHistoryAndDoesNotReapply() {
        String schema = migrationSchema();
        try {
            migrateTo(schema, "6").migrate();
            Fixture fixture = fixture(schema);
            UUID original = location(schema, fixture.encounter(), fixture, fixture.bed(), START, START.plusHours(1));
            UUID restored = location(schema, fixture.encounter(), fixture, fixture.bed(), START.plusHours(1), null);
            jdbc.update("INSERT INTO " + schema + ".encounter_discharges "
                            + "(id, encounter_id, location_id, discharged_at, cancelled_at, cancelled_by, restored_location_id) "
                            + "VALUES (?, ?, ?, ?, ?, 'test-clerk', ?)",
                    UUID.randomUUID(), fixture.encounter(), original, START.plusHours(1), START.plusHours(2), restored);
            UUID physician = UUID.randomUUID();
            jdbc.update("INSERT INTO " + schema + ".physicians "
                            + "(id, physician_code, first_name, last_name, active, version) VALUES (?, ?, 'Test', 'Doctor', true, 0)",
                    physician, physician.toString().substring(0, 20));
            jdbc.update("INSERT INTO " + schema + ".physician_departments (physician_id, department_id) VALUES (?, ?)",
                    physician, fixture.department());
            jdbc.update("INSERT INTO " + schema + ".encounter_physician_assignments "
                            + "(id, encounter_id, physician_id, department_id, started_at, assigned_by, version) "
                            + "VALUES (?, ?, ?, ?, ?, 'test-clerk', 0)",
                    UUID.randomUUID(), fixture.encounter(), physician, fixture.department(), START.plusHours(2));
            var before = snapshot(schema);

            Flyway upgrade = migrateTo(schema, "7");
            assertThat(upgrade.migrate().migrationsExecuted).isEqualTo(1);
            assertThat(upgrade.migrate().migrationsExecuted).isZero();
            assertThat(snapshot(schema)).isEqualTo(before);
            assertThat(jdbc.queryForObject("SELECT count(*) FROM " + schema
                    + ".flyway_schema_history WHERE version = '7' AND success", Integer.class)).isEqualTo(1);
            assertThatThrownBy(() -> location(schema, fixture.encounter(), fixture, null, START.plusHours(3), null))
                    .isInstanceOf(DataIntegrityViolationException.class)
                    .hasMessageContaining("uk_encounter_locations_open_encounter");
        } finally {
            jdbc.execute("DROP SCHEMA IF EXISTS " + schema + " CASCADE");
        }
    }

    @ParameterizedTest
    @ValueSource(strings = {"active-patient", "open-encounter", "open-bed", "negative-time"})
    void refusesInvalidLegacyDataWithoutChangingRecordsOrInstallingPartialConstraints(String problem) {
        String schema = migrationSchema();
        try {
            migrateTo(schema, "6").migrate();
            Fixture fixture = fixture(schema);
            location(schema, fixture.encounter(), fixture, fixture.bed(), START, null);
            String message = switch (problem) {
                case "active-patient" -> {
                    encounter(schema, fixture.patient(), "ADMITTED");
                    yield "A patient has multiple active encounters";
                }
                case "open-encounter" -> {
                    location(schema, fixture.encounter(), fixture, null, START.plusHours(1), null);
                    yield "An encounter has multiple open locations";
                }
                case "open-bed" -> {
                    location(schema, encounter(schema, patient(schema), "IN_DEPARTMENT"), fixture, fixture.bed(), START, null);
                    yield "A bed has multiple open occupancies";
                }
                case "negative-time" -> {
                    location(schema, fixture.encounter(), fixture, null, START, START.minusSeconds(1));
                    yield "A location ends before it starts";
                }
                default -> throw new IllegalArgumentException(problem);
            };
            var before = snapshot(schema);

            assertThatThrownBy(() -> migrateTo(schema, "7").migrate())
                    .isInstanceOf(FlywayException.class).hasStackTraceContaining(message);

            assertThat(snapshot(schema)).isEqualTo(before);
            assertThat(jdbc.queryForObject("SELECT count(*) FROM " + schema
                    + ".flyway_schema_history WHERE version = '7'", Integer.class)).isZero();
            assertThat(jdbc.queryForList("SELECT indexname FROM pg_indexes WHERE schemaname = ?", String.class, schema))
                    .doesNotContain("uk_encounters_active_patient", "uk_encounter_locations_open_encounter",
                            "uk_encounter_locations_open_bed");
            assertThat(jdbc.queryForObject("SELECT count(*) FROM pg_constraint c JOIN pg_namespace n ON n.oid = c.connamespace "
                    + "WHERE n.nspname = ? AND c.conname = 'ck_encounter_locations_time'", Integer.class, schema)).isZero();
        } finally {
            jdbc.execute("DROP SCHEMA IF EXISTS " + schema + " CASCADE");
        }
    }

    @ParameterizedTest
    @ValueSource(strings = {"ADMITTED", "IN_DEPARTMENT"})
    void rejectsAnotherActiveEncounterOnInsertAndReactivation(String activeStatus) {
        UUID patient = patient(SCHEMA);
        encounter(SCHEMA, patient, activeStatus);
        assertThatThrownBy(() -> encounter(SCHEMA, patient, "ADMITTED"))
                .isInstanceOf(DataIntegrityViolationException.class).hasMessageContaining("uk_encounters_active_patient");
        UUID closed = encounter(SCHEMA, patient, "DISCHARGED");
        assertThatThrownBy(() -> jdbc.update("UPDATE encounters SET status = 'IN_DEPARTMENT' WHERE id = ?", closed))
                .isInstanceOf(DataIntegrityViolationException.class).hasMessageContaining("uk_encounters_active_patient");
        assertThat(jdbc.queryForObject("SELECT status FROM encounters WHERE id = ?", String.class, closed)).isEqualTo("DISCHARGED");
    }

    @Test
    void rejectsAnotherOpenLocationOnInsertAndReopening() {
        Fixture fixture = fixture(SCHEMA);
        location(SCHEMA, fixture.encounter(), fixture, fixture.bed(), START, null);
        assertThatThrownBy(() -> location(SCHEMA, fixture.encounter(), fixture, null, START, null))
                .isInstanceOf(DataIntegrityViolationException.class).hasMessageContaining("uk_encounter_locations_open_encounter");
        UUID closed = location(SCHEMA, fixture.encounter(), fixture, null, START.minusHours(1), START);
        assertThatThrownBy(() -> jdbc.update("UPDATE encounter_locations SET ended_at = NULL WHERE id = ?", closed))
                .isInstanceOf(DataIntegrityViolationException.class).hasMessageContaining("uk_encounter_locations_open_encounter");
        assertThat(jdbc.queryForObject("SELECT ended_at FROM encounter_locations WHERE id = ?", OffsetDateTime.class, closed))
                .isEqualTo(START);
    }

    @Test
    void rejectsAnotherOpenBedOccupancyOnInsertAndBedChange() {
        Fixture fixture = fixture(SCHEMA);
        location(SCHEMA, fixture.encounter(), fixture, fixture.bed(), START, null);
        UUID otherEncounter = encounter(SCHEMA, patient(SCHEMA), "IN_DEPARTMENT");
        assertThatThrownBy(() -> location(SCHEMA, otherEncounter, fixture, fixture.bed(), START, null))
                .isInstanceOf(DataIntegrityViolationException.class).hasMessageContaining("uk_encounter_locations_open_bed");
        UUID unassigned = location(SCHEMA, otherEncounter, fixture, null, START, null);
        assertThatThrownBy(() -> jdbc.update("UPDATE encounter_locations SET bed_id = ? WHERE id = ?", fixture.bed(), unassigned))
                .isInstanceOf(DataIntegrityViolationException.class).hasMessageContaining("uk_encounter_locations_open_bed");
        assertThat(jdbc.queryForObject("SELECT bed_id FROM encounter_locations WHERE id = ?", UUID.class, unassigned)).isNull();
    }

    @Test
    void allowsClosedEncountersRepeatedBedHistoryAndMultipleUnassignedPatients() {
        Fixture fixture = fixture(SCHEMA);
        encounter(SCHEMA, fixture.patient(), "DISCHARGED");
        encounter(SCHEMA, fixture.patient(), "DISCHARGED");
        encounter(SCHEMA, fixture.patient(), "ADMISSION_CANCELLED");
        location(SCHEMA, fixture.encounter(), fixture, fixture.bed(), START.minusHours(1), START);
        location(SCHEMA, fixture.encounter(), fixture, fixture.bed(), START, START); // Equal-time corrections are valid.
        location(SCHEMA, fixture.encounter(), fixture, null, START, null);
        UUID other = encounter(SCHEMA, patient(SCHEMA), "IN_DEPARTMENT");
        location(SCHEMA, other, fixture, null, START, null);
        UUID third = encounter(SCHEMA, patient(SCHEMA), "IN_DEPARTMENT");
        location(SCHEMA, third, fixture, fixture.bed(), START, null);
        assertThat(jdbc.queryForObject("SELECT count(*) FROM encounter_locations WHERE ward_id = ? AND ended_at IS NULL",
                Integer.class, fixture.ward())).isEqualTo(3);
    }

    @Test
    void rejectsNegativeLocationIntervalsOnInsertAndUpdate() {
        Fixture fixture = fixture(SCHEMA);
        assertThatThrownBy(() -> location(SCHEMA, fixture.encounter(), fixture, null, START, START.minusNanos(1000)))
                .isInstanceOf(DataIntegrityViolationException.class).hasMessageContaining("ck_encounter_locations_time");
        UUID open = location(SCHEMA, fixture.encounter(), fixture, null, START, null);
        assertThatThrownBy(() -> jdbc.update("UPDATE encounter_locations SET ended_at = ? WHERE id = ?", START.minusSeconds(1), open))
                .isInstanceOf(DataIntegrityViolationException.class).hasMessageContaining("ck_encounter_locations_time");
        jdbc.update("UPDATE encounter_locations SET ended_at = started_at WHERE id = ?", open);
        assertThatThrownBy(() -> jdbc.update("UPDATE encounter_locations SET started_at = ? WHERE id = ?", START.plusSeconds(1), open))
                .isInstanceOf(DataIntegrityViolationException.class).hasMessageContaining("ck_encounter_locations_time");
    }

    @ParameterizedTest
    @CsvSource({"active-patient, false", "active-patient, true", "open-encounter, false",
            "open-encounter, true", "open-bed, false", "open-bed, true"})
    void competingDirectWritesWaitForCommitOrRollback(String rule, boolean rollBackFirst) throws Exception {
        Fixture fixture = fixture(SCHEMA);
        Supplier<UUID> firstWrite;
        Supplier<UUID> secondWrite;
        String table;
        String constraint;
        switch (rule) {
            case "active-patient" -> {
                jdbc.update("UPDATE encounters SET status = 'DISCHARGED' WHERE id = ?", fixture.encounter());
                firstWrite = () -> encounter(SCHEMA, fixture.patient(), "ADMITTED");
                secondWrite = () -> encounter(SCHEMA, fixture.patient(), "IN_DEPARTMENT");
                table = "encounters";
                constraint = "uk_encounters_active_patient";
            }
            case "open-encounter" -> {
                firstWrite = () -> location(SCHEMA, fixture.encounter(), fixture, null, START, null);
                secondWrite = () -> location(SCHEMA, fixture.encounter(), fixture, null, START, null);
                table = "encounter_locations";
                constraint = "uk_encounter_locations_open_encounter";
            }
            case "open-bed" -> {
                UUID otherEncounter = encounter(SCHEMA, patient(SCHEMA), "IN_DEPARTMENT");
                firstWrite = () -> location(SCHEMA, fixture.encounter(), fixture, fixture.bed(), START, null);
                secondWrite = () -> location(SCHEMA, otherEncounter, fixture, fixture.bed(), START, null);
                table = "encounter_locations";
                constraint = "uk_encounter_locations_open_bed";
            }
            default -> throw new IllegalArgumentException(rule);
        }
        var transactions = transactions();
        var firstWritten = new CountDownLatch(1);
        var releaseFirst = new CountDownLatch(1);
        var firstBackend = new AtomicInteger();
        var executor = Executors.newFixedThreadPool(2);
        try {
            var first = executor.submit(() -> transactions.execute(status -> {
                firstBackend.set(jdbc.queryForObject("SELECT pg_backend_pid()", Integer.class));
                UUID id = firstWrite.get();
                firstWritten.countDown();
                awaitRelease(releaseFirst);
                if (rollBackFirst) {
                    status.setRollbackOnly();
                }
                return id;
            }));
            assertThat(firstWritten.await(10, TimeUnit.SECONDS)).isTrue();
            var second = executor.submit(() -> transactions.execute(status -> secondWrite.get()));
            // No service or explicit row lock: the unique index itself must serialize these writes.
            awaitBlockedBy(second, firstBackend.get());
            releaseFirst.countDown();

            UUID firstId = first.get(10, TimeUnit.SECONDS);
            if (rollBackFirst) {
                UUID secondId = second.get(10, TimeUnit.SECONDS);
                assertThat(jdbc.queryForObject("SELECT count(*) FROM " + table + " WHERE id = ?", Integer.class, firstId)).isZero();
                assertThat(jdbc.queryForObject("SELECT count(*) FROM " + table + " WHERE id = ?", Integer.class, secondId)).isEqualTo(1);
            } else {
                assertThatThrownBy(() -> second.get(10, TimeUnit.SECONDS)).isInstanceOf(ExecutionException.class)
                        .hasCauseInstanceOf(DataIntegrityViolationException.class).hasStackTraceContaining(constraint);
                assertThat(jdbc.queryForObject("SELECT count(*) FROM " + table + " WHERE id = ?", Integer.class, firstId)).isEqualTo(1);
            }
            String count = switch (rule) {
                case "active-patient" -> "SELECT count(*) FROM encounters WHERE patient_id = ? AND status IN ('ADMITTED', 'IN_DEPARTMENT')";
                case "open-encounter" -> "SELECT count(*) FROM encounter_locations WHERE encounter_id = ? AND ended_at IS NULL";
                default -> "SELECT count(*) FROM encounter_locations WHERE bed_id = ? AND ended_at IS NULL";
            };
            UUID key = switch (rule) {
                case "active-patient" -> fixture.patient();
                case "open-encounter" -> fixture.encounter();
                default -> fixture.bed();
            };
            assertThat(jdbc.queryForObject(count, Integer.class, key)).isEqualTo(1);
        } finally {
            releaseFirst.countDown();
            executor.shutdownNow();
            assertThat(executor.awaitTermination(10, TimeUnit.SECONDS)).isTrue();
        }
    }

    @ParameterizedTest
    @ValueSource(strings = {"same-bed", "different-bed", "no-bed"})
    void transfersDepartmentsWithoutViolatingOpenLocationOrBedUniqueness(String destination) {
        Fixture fixture = fixture(SCHEMA);
        UUID initial = location(SCHEMA, fixture.encounter(), fixture, fixture.bed(), START, null);
        UUID assignment = assignPhysician(fixture, initial);
        UUID department = department();
        UUID targetBed = switch (destination) {
            case "same-bed" -> fixture.bed();
            case "different-bed" -> {
                UUID bed = UUID.randomUUID();
                jdbc.update("INSERT INTO beds VALUES (?, '02', ?, true)", bed, fixture.ward());
                yield bed;
            }
            default -> null;
        };

        var next = encounterService.transferEncounter(fixture.encounter(), department, fixture.ward(), targetBed,
                START.plusHours(1), "test-clerk", initial);

        var timeline = encounterService.getTimeline(fixture.encounter());
        assertThat(timeline.locations()).hasSize(2);
        assertThat(timeline.locations().getFirst().id()).isEqualTo(initial);
        assertThat(timeline.locations().getFirst().endedAt()).isEqualTo(START.plusHours(1));
        assertThat(timeline.locations().getLast().id()).isEqualTo(next.getId());
        assertThat(timeline.locations().getLast().endedAt()).isNull();
        assertThat(timeline.locations().getLast().bedId()).isEqualTo(targetBed);
        var responsibility = physicianService.getAssignments(fixture.encounter());
        assertThat(responsibility.currentAssignmentId()).isNull();
        assertThat(responsibility.assignments()).singleElement().satisfies(row -> {
            assertThat(row.id()).isEqualTo(assignment);
            assertThat(row.endReason()).isEqualTo(PhysicianAssignmentEndReason.DEPARTMENT_TRANSFER);
        });
    }

    @Test
    void rollsBackLocationAndPhysicianClosureAfterReplacementHasBeenFlushed() {
        Fixture fixture = fixture(SCHEMA);
        UUID initial = location(SCHEMA, fixture.encounter(), fixture, fixture.bed(), START, null);
        assignPhysician(fixture, initial);
        UUID nextDepartment = department();
        var before = encounterService.getTimeline(fixture.encounter());
        var responsibility = physicianService.getAssignments(fixture.encounter());

        assertThatThrownBy(() -> transactions().executeWithoutResult(status -> {
            encounterService.transferEncounter(fixture.encounter(), nextDepartment, fixture.ward(), fixture.bed(),
                    START.plusHours(1), "test-clerk", initial);
            entityManager.flush();
            assertThat(jdbc.queryForObject("SELECT count(*) FROM encounter_locations WHERE encounter_id = ?",
                    Integer.class, fixture.encounter())).isEqualTo(2);
            assertThat(jdbc.queryForObject("SELECT count(*) FROM encounter_physician_assignments "
                    + "WHERE encounter_id = ? AND ended_at IS NULL", Integer.class, fixture.encounter())).isZero();
            throw new IllegalStateException("Failure after transfer reached the database");
        })).isInstanceOf(IllegalStateException.class).hasMessage("Failure after transfer reached the database");

        assertThat(encounterService.getTimeline(fixture.encounter())).isEqualTo(before);
        assertThat(physicianService.getAssignments(fixture.encounter())).isEqualTo(responsibility);
        assertThat(jdbc.queryForObject("SELECT id FROM encounter_locations WHERE bed_id = ? AND ended_at IS NULL",
                UUID.class, fixture.bed())).isEqualTo(initial);
    }

    @ParameterizedTest
    @ValueSource(booleans = {true, false})
    void dischargeCorrectionAndReadmissionReuseReleasedKeys(boolean withBed) {
        Fixture fixture = fixture(SCHEMA);
        UUID bed = withBed ? fixture.bed() : null;
        UUID initial = location(SCHEMA, fixture.encounter(), fixture, bed, START, null);
        assignPhysician(fixture, initial);
        encounterService.dischargeEncounter(fixture.encounter(), START.plusHours(1), "test-clerk", initial);
        var discharged = encounterService.getTimeline(fixture.encounter());
        UUID dischargeId = discharged.discharges().getFirst().id();

        assertThatThrownBy(() -> transactions().executeWithoutResult(status -> {
            encounterService.cancelDischarge(fixture.encounter(), START.plusHours(2), "test-clerk", dischargeId);
            entityManager.flush();
            assertThat(jdbc.queryForObject("SELECT count(*) FROM encounter_locations WHERE encounter_id = ? AND ended_at IS NULL",
                    Integer.class, fixture.encounter())).isEqualTo(1);
            throw new IllegalStateException("Failure after discharge correction reached the database");
        })).isInstanceOf(IllegalStateException.class).hasMessage("Failure after discharge correction reached the database");
        assertThat(encounterService.getTimeline(fixture.encounter())).isEqualTo(discharged);

        encounterService.cancelDischarge(fixture.encounter(), START.plusHours(2), "test-clerk", dischargeId);
        var restored = encounterService.getTimeline(fixture.encounter());
        assertThat(restored.encounter().status()).isEqualTo(EncounterStatus.IN_DEPARTMENT);
        assertThat(restored.locations()).hasSize(2);
        assertThat(restored.locations().getLast().bedId()).isEqualTo(bed);
        assertThat(restored.locations().getLast().endedAt()).isNull();
        assertThat(physicianService.getAssignments(fixture.encounter()).currentAssignmentId()).isNull();
        encounterService.dischargeEncounter(fixture.encounter(), START.plusHours(3), "test-clerk", restored.locations().getLast().id());
        var finalHistory = encounterService.getTimeline(fixture.encounter());
        var readmitted = encounterService.admitPatient(fixture.patient(), UUID.randomUUID().toString(), START.plusHours(4));
        encounterService.admitToDepartment(readmitted.getId(), fixture.department(), fixture.ward(), bed, START.plusHours(5));

        assertThatThrownBy(() -> encounterService.cancelDischarge(fixture.encounter(), START.plusHours(6), "test-clerk"))
                .isInstanceOf(ActiveEncounterExistsException.class);
        assertThat(encounterService.getTimeline(fixture.encounter())).isEqualTo(finalHistory);
        assertThat(jdbc.queryForObject("SELECT id FROM encounters WHERE patient_id = ? AND status IN ('ADMITTED', 'IN_DEPARTMENT')",
                UUID.class, fixture.patient())).isEqualTo(readmitted.getId());
    }

    private UUID assignPhysician(Fixture fixture, UUID location) {
        UUID physician = UUID.randomUUID();
        jdbc.update("INSERT INTO physicians VALUES (?, ?, 'Test', 'Doctor', true, 0)", physician, physician.toString().substring(0, 20));
        jdbc.update("INSERT INTO physician_departments VALUES (?, ?)", physician, fixture.department());
        return physicianService.assign(fixture.encounter(), physician, location, null, START, "test-clerk").getId();
    }

    private UUID department() {
        UUID id = UUID.randomUUID();
        jdbc.update("INSERT INTO departments VALUES (?, ?, 'Test Rehabilitation', true)", id, id.toString().substring(0, 20));
        return id;
    }

    private TransactionTemplate transactions() {
        var transactions = new TransactionTemplate(transactionManager);
        transactions.setTimeout(20);
        return transactions;
    }

    private void awaitBlockedBy(Future<?> contender, int blocker) throws Exception {
        long deadline = System.nanoTime() + TimeUnit.SECONDS.toNanos(5);
        while (System.nanoTime() < deadline) {
            if (contender.isDone()) {
                contender.get();
                throw new AssertionError("The second write completed without waiting for the first transaction");
            }
            if (Boolean.TRUE.equals(jdbc.queryForObject("""
                    SELECT EXISTS (SELECT 1 FROM pg_stat_activity
                    WHERE datname = current_database() AND ? = ANY(pg_blocking_pids(pid)))
                    """, Boolean.class, blocker))) {
                return;
            }
            Thread.sleep(25);
        }
        throw new AssertionError("PostgreSQL did not report the expected blocked write");
    }

    private static void awaitRelease(CountDownLatch release) {
        try {
            if (!release.await(15, TimeUnit.SECONDS)) {
                throw new AssertionError("Timed out waiting to finish the first transaction");
            }
        } catch (InterruptedException exception) {
            Thread.currentThread().interrupt();
            throw new IllegalStateException("First transaction was interrupted", exception);
        }
    }

    private Flyway migrateTo(String schema, String version) {
        return Flyway.configure().dataSource(jdbc.getDataSource()).locations("classpath:db/migration/postgresql")
                .schemas(schema).defaultSchema(schema).target(version).load();
    }

    private Map<String, List<Map<String, Object>>> snapshot(String schema) {
        var result = new LinkedHashMap<String, List<Map<String, Object>>>();
        for (String table : TABLES) {
            result.put(table, jdbc.queryForList("SELECT * FROM " + schema + "." + table + " ORDER BY 1, 2"));
        }
        return result;
    }

    private UUID patient(String schema) {
        UUID id = UUID.randomUUID();
        jdbc.update("INSERT INTO " + schema + ".patients VALUES (?, ?, 'Test', 'Patient', DATE '1990-05-14')", id, id.toString());
        return id;
    }

    private UUID encounter(String schema, UUID patient, String status) {
        UUID id = UUID.randomUUID();
        jdbc.update("INSERT INTO " + schema + ".encounters (id, encounter_number, patient_id, status, admitted_at) "
                + "VALUES (?, ?, ?, ?, ?)", id, id.toString(), patient, status, START.minusHours(1));
        return id;
    }

    private Fixture fixture(String schema) {
        UUID department = UUID.randomUUID();
        UUID ward = UUID.randomUUID();
        UUID bed = UUID.randomUUID();
        jdbc.update("INSERT INTO " + schema + ".departments VALUES (?, ?, 'Test Medicine', true)", department, department.toString().substring(0, 20));
        jdbc.update("INSERT INTO " + schema + ".wards VALUES (?, ?, 'Test Ward', true)", ward, ward.toString().substring(0, 20));
        jdbc.update("INSERT INTO " + schema + ".beds VALUES (?, '01', ?, true)", bed, ward);
        UUID patient = patient(schema);
        return new Fixture(patient, encounter(schema, patient, "IN_DEPARTMENT"), department, ward, bed);
    }

    private UUID location(String schema, UUID encounter, Fixture fixture, UUID bed, OffsetDateTime start, OffsetDateTime end) {
        UUID id = UUID.randomUUID();
        jdbc.update("INSERT INTO " + schema + ".encounter_locations "
                + "(id, encounter_id, department_id, ward_id, bed_id, started_at, ended_at) VALUES (?, ?, ?, ?, ?, ?, ?)",
                id, encounter, fixture.department(), fixture.ward(), bed, start, end);
        return id;
    }

    private static String migrationSchema() {
        return "clinicflow_v7_" + UUID.randomUUID().toString().replace("-", "");
    }

    private static String requiredEnvironment(String name) {
        String value = System.getenv(name);
        if (value == null || value.isBlank()) {
            throw new IllegalArgumentException(name + " is required when TEST_DATABASE_URL is set");
        }
        return value;
    }

    private record Fixture(UUID patient, UUID encounter, UUID department, UUID ward, UUID bed) {
    }
}
