package com.jiangyudai.clinicflow.web.error;

/** Stable API identifiers; changing presentation text must not change client behaviour. */
public enum ApiErrorCode {
    INVALID_PHYSICIAN_ASSIGNMENT,
    PHYSICIAN_ASSIGNMENT_CONFLICT,
    PHYSICIAN_NOT_FOUND,
    DUPLICATE_PHYSICIAN_CODE,
    UPDATE_CONFLICT,
    INVALID_PHYSICIAN_DEPARTMENT,
    DUPLICATE_ENCOUNTER_NUMBER,
    ACTIVE_ENCOUNTER_EXISTS,
    ENCOUNTER_HISTORY_CONFLICT,
    ENCOUNTER_NOT_FOUND,
    INVALID_ADMISSION_TIME,
    INVALID_DISCHARGE_TIME,
    INVALID_ADMISSION_CANCELLATION,
    INVALID_DISCHARGE_CANCELLATION,
    DUPLICATE_MEDICAL_RECORD_NUMBER,
    PATIENT_NOT_FOUND,
    INVALID_REQUEST,
    ENCOUNTER_LOCATION_CONFLICT,
    INVALID_LOCATION,
    LOCATION_NOT_FOUND,
    BED_HISTORY_CONFLICT,
    SUBSEQUENT_ENCOUNTER_EXISTS,
    BED_OCCUPIED,
    SIGN_IN_FAILED,
    AUTHENTICATION_REQUIRED,
    CSRF_REJECTED,
    ACCESS_DENIED
}
